#!/usr/bin/env bash
set -euo pipefail

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/common.sh"

thinwedge_require_command python3

thinwedge_home=${1:-$(thinwedge_thinwedge_home)}
workspace_root=${2:-$(mktemp -d)}
script_root=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
model_repo_root="$workspace_root/model-pricing-repo"
environment_repo_root="$workspace_root/env-pricing-repo"
if [[ -n "${THINWEDGE_FIXTURE_RUNPOD_TEMPLATE_ID+x}" ]]; then
  runpod_template_id=${THINWEDGE_FIXTURE_RUNPOD_TEMPLATE_ID}
else
  runpod_template_id=tmpl-thinwedge-pricing
fi
runpod_gpu_type_id=${THINWEDGE_FIXTURE_RUNPOD_GPU_TYPE_ID:-NVIDIA A100 80GB PCIe}
runpod_network_volume_id=${THINWEDGE_FIXTURE_RUNPOD_NETWORK_VOLUME_ID:-}
runpod_cloud_type=${THINWEDGE_FIXTURE_RUNPOD_CLOUD_TYPE:-SECURE}
runpod_support_public_ip=${THINWEDGE_FIXTURE_RUNPOD_SUPPORT_PUBLIC_IP:-true}
runpod_ssh_public_key=${THINWEDGE_FIXTURE_RUNPOD_SSH_PUBLIC_KEY:-}
runpod_ssh_private_key_path=${THINWEDGE_FIXTURE_RUNPOD_SSH_PRIVATE_KEY_PATH:-}
runpod_image_name=${THINWEDGE_FIXTURE_RUNPOD_IMAGE_NAME:-}
runpod_docker_entrypoint_json=${THINWEDGE_FIXTURE_RUNPOD_DOCKER_ENTRYPOINT_JSON:-}
runpod_docker_start_cmd_json=${THINWEDGE_FIXTURE_RUNPOD_DOCKER_START_CMD_JSON:-}
runpod_global_networking=${THINWEDGE_FIXTURE_RUNPOD_GLOBAL_NETWORKING:-true}
if [[ -n "${THINWEDGE_FIXTURE_RUNPOD_CONTROL_TOKEN+x}" ]]; then
  runpod_control_token=${THINWEDGE_FIXTURE_RUNPOD_CONTROL_TOKEN}
else
  runpod_control_token=$(thinwedge_uuid)
fi
if [[ -n "${THINWEDGE_FIXTURE_RUNPOD_CONTROL_PORT+x}" ]]; then
  runpod_control_port=${THINWEDGE_FIXTURE_RUNPOD_CONTROL_PORT}
else
  runpod_control_port=8000
fi
runtime_family=${THINWEDGE_FIXTURE_RUNTIME_FAMILY:-rapids}
control_server_b64=$(
  THINWEDGE_CONTROL_SERVER_PATH="$script_root/pod_control_server.py" python3 - <<'PYCODE'
import base64
import os
import pathlib

payload = pathlib.Path(os.environ["THINWEDGE_CONTROL_SERVER_PATH"]).read_bytes()
print(base64.b64encode(payload).decode("ascii"))
PYCODE
)
default_runpod_docker_start_cmd_json=$(
  THINWEDGE_FIXTURE_RUNPOD_CONTROL_PORT="$runpod_control_port" python3 - <<'PYCODE'
import json
import os

command = r"""python3 - <<'PY'
import base64
import os
import pathlib

payload = base64.b64decode(os.environ["THINWEDGE_CONTROL_SERVER_B64"])
path = pathlib.Path("/opt/thinwedge-pod-control-server.py")
path.write_bytes(payload)
PY
mkdir -p /workspace/thinwedge
exec python3 /opt/thinwedge-pod-control-server.py"""
print(json.dumps(["bash", "-lc", command]))
PYCODE
)
if [[ -z "$runpod_docker_start_cmd_json" ]]; then
  runpod_docker_start_cmd_json=$default_runpod_docker_start_cmd_json
fi

mkdir -p "$model_repo_root/scripts" "$environment_repo_root/ops" "$environment_repo_root/workdir"
cat >"$model_repo_root/config.yaml" <<'EOF'
model: model-pricing
trainer: thinwedge
EOF

cat >"$model_repo_root/scripts/train.sh" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail

payload=""
output_dir=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --thinwedge-payload)
      payload=$2
      shift 2
      ;;
    --thinwedge-output-dir)
      output_dir=$2
      shift 2
      ;;
    *)
      shift
      ;;
  esac
done

python3 - <<'PY' "$payload" "$output_dir"
import json
import os
import pathlib
import time
import sys

payload_path = pathlib.Path(sys.argv[1])
output_dir = pathlib.Path(sys.argv[2])
repository_root = pathlib.Path.cwd()
output_dir.mkdir(parents=True, exist_ok=True)
payload = json.loads(payload_path.read_text(encoding="utf-8"))

generated_files = []
for entry in ((payload.get("codegen") or {}).get("files")) or []:
    target_path = repository_root / entry["path"]
    target_path.parent.mkdir(parents=True, exist_ok=True)
    target_path.write_text(
        "# generated by ThinWedge sample trainer\n"
        f"MODEL_ID = {os.environ['THINWEDGE_MODEL_ID']!r}\n"
        "def build_model(config):\n"
        "    return {\"model_id\": MODEL_ID, \"config\": config}\n",
        encoding="utf-8",
    )
    generated_files.append(
        {
            "path": entry["path"],
            "remotePath": str(target_path),
            "mode": "live",
        }
    )

training_manifest = {
    "jobId": os.environ["THINWEDGE_JOB_ID"],
    "modelId": os.environ["THINWEDGE_MODEL_ID"],
    "environmentId": os.environ["THINWEDGE_ENVIRONMENT_ID"],
    "provider": "runpod",
    "podId": os.environ.get("RUNPOD_POD_ID"),
    "workspacePath": os.environ.get("PWD"),
    "remoteCommand": "sample-remote-trainer",
    "payload": payload,
    "generatedFiles": generated_files,
    "status": "completed",
    "generatedAt": int(time.time()),
}
eval_manifest = {
    "id": f"eval-{os.environ['THINWEDGE_JOB_ID']}",
    "jobId": os.environ["THINWEDGE_JOB_ID"],
    "modelId": os.environ["THINWEDGE_MODEL_ID"],
    "status": "completed",
    "summary": f"Training completed for {os.environ['THINWEDGE_MODEL_ID']}",
    "metrics": {
        "epochs": payload.get("epochs"),
        "learningRate": payload.get("learningRate"),
        "dataset": payload.get("dataset"),
        "generatedFileCount": len(generated_files),
    },
    "artifactPaths": [os.environ["THINWEDGE_REMOTE_TRAINING_MANIFEST_PATH"]],
    "createdAt": int(time.time()),
}
codegen_manifest = {"generatedFiles": generated_files}

pathlib.Path(os.environ["THINWEDGE_REMOTE_TRAINING_MANIFEST_PATH"]).write_text(
    json.dumps(training_manifest, indent=2) + "\n",
    encoding="utf-8",
)
pathlib.Path(os.environ["THINWEDGE_REMOTE_EVAL_MANIFEST_PATH"]).write_text(
    json.dumps(eval_manifest, indent=2) + "\n",
    encoding="utf-8",
)
pathlib.Path(os.environ["THINWEDGE_REMOTE_CODEGEN_MANIFEST_PATH"]).write_text(
    json.dumps(codegen_manifest, indent=2) + "\n",
    encoding="utf-8",
)
print(json.dumps({"status": "completed", "generatedFiles": generated_files}))
PY
EOF

cat >"$model_repo_root/scripts/batch_infer.sh" <<EOF
#!/usr/bin/env bash
set -euo pipefail
exec bash "$script_root/batch_infer.sh" "\$@"
EOF

cat >"$model_repo_root/scripts/run_batch_inference.py" <<'EOF'
#!/usr/bin/env python3
import argparse
import json
import os
import pathlib
import time


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--thinwedge-payload", required=True)
    parser.add_argument("--thinwedge-output-dir", required=True)
    args = parser.parse_args()

    with open(args.thinwedge_payload, encoding="utf-8") as handle:
        payload = json.load(handle)

    output_path = pathlib.Path(payload["outputPath"])
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        json.dumps(
            [
                {
                    "jobId": os.environ.get("THINWEDGE_JOB_ID"),
                    "modelId": os.environ.get("THINWEDGE_MODEL_ID"),
                    "environmentId": os.environ.get("THINWEDGE_ENVIRONMENT_ID"),
                    "prediction": "fixture",
                }
            ],
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )

    artifact_manifest_path = pathlib.Path(
        os.environ.get("THINWEDGE_REMOTE_BATCH_ARTIFACT_MANIFEST_PATH")
        or pathlib.Path(args.thinwedge_output_dir) / "batch-artifact-manifest.json"
    )
    eval_manifest_path = pathlib.Path(
        os.environ.get("THINWEDGE_REMOTE_BATCH_EVAL_MANIFEST_PATH")
        or pathlib.Path(args.thinwedge_output_dir) / "batch-eval-manifest.json"
    )
    artifact_manifest_path.parent.mkdir(parents=True, exist_ok=True)
    eval_manifest_path.parent.mkdir(parents=True, exist_ok=True)

    artifact_manifest = {
        "jobId": os.environ.get("THINWEDGE_JOB_ID"),
        "modelId": os.environ.get("THINWEDGE_MODEL_ID"),
        "environmentId": os.environ.get("THINWEDGE_ENVIRONMENT_ID"),
        "provider": "runpod",
        "inputPath": payload.get("inputPath"),
        "inputUri": payload.get("inputUri"),
        "outputPath": payload.get("outputPath"),
        "rowCount": 1,
        "executionMode": "ssh",
        "generatedAt": int(time.time()),
    }
    eval_manifest = {
        "id": f"eval-{os.environ.get('THINWEDGE_JOB_ID')}",
        "jobId": os.environ.get("THINWEDGE_JOB_ID"),
        "modelId": os.environ.get("THINWEDGE_MODEL_ID"),
        "status": "completed",
        "summary": f"Batch inference completed for {os.environ.get('THINWEDGE_MODEL_ID')}",
        "metrics": {
            "batchSize": payload.get("batchSize"),
            "shardIndex": payload.get("shardIndex"),
            "shardCount": payload.get("shardCount"),
            "rowCount": 1,
            "executionMode": "ssh",
        },
        "artifactPaths": [str(artifact_manifest_path), payload.get("outputPath")],
        "createdAt": int(time.time()),
    }
    artifact_manifest_path.write_text(json.dumps(artifact_manifest, indent=2) + "\n", encoding="utf-8")
    eval_manifest_path.write_text(json.dumps(eval_manifest, indent=2) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
EOF

cat >"$environment_repo_root/ops/launch.sh" <<EOF
#!/usr/bin/env bash
set -euo pipefail
exec bash "$script_root/launch.sh" "\$@"
EOF

cat >"$environment_repo_root/ops/attach.sh" <<EOF
#!/usr/bin/env bash
set -euo pipefail
exec bash "$script_root/attach.sh" "\$@"
EOF

cat >"$environment_repo_root/ops/stop.sh" <<EOF
#!/usr/bin/env bash
set -euo pipefail
exec bash "$script_root/stop.sh" "\$@"
EOF

chmod +x \
  "$model_repo_root/scripts/train.sh" \
  "$model_repo_root/scripts/batch_infer.sh" \
  "$model_repo_root/scripts/run_batch_inference.py" \
  "$environment_repo_root/ops/launch.sh" \
  "$environment_repo_root/ops/attach.sh" \
  "$environment_repo_root/ops/stop.sh"

cat >"$environment_repo_root/ops/README.md" <<'EOF'
# ThinWedge environment repo wrappers
EOF

models_path="$thinwedge_home/thinwedge/ml/statisticalmodels.json"
environments_path="$thinwedge_home/thinwedge/ml/trainingenvironments.json"
mkdir -p "$(dirname "$models_path")"

THINWEDGE_FIXTURE_MODEL_REPO_ROOT="$model_repo_root" \
THINWEDGE_FIXTURE_ENV_REPO_ROOT="$environment_repo_root" \
THINWEDGE_FIXTURE_SCRIPT_ROOT="$script_root" \
python3 - <<'PY' | thinwedge_write_json_file "$models_path"
import json
import os

script_root = os.environ["THINWEDGE_FIXTURE_SCRIPT_ROOT"]
model_repo_root = os.environ["THINWEDGE_FIXTURE_MODEL_REPO_ROOT"]
payload = {
    "models": [
        {
            "id": "model-pricing",
            "name": "Pricing Model",
            "description": "ThinWedge sample pricing model",
            "tags": ["pricing", "gpu"],
            "visibleToRoles": ["pricing_researcher"],
            "defaultEnvironmentId": "env-pricing",
            "repository": {
                "root": model_repo_root,
                "configPath": f"{model_repo_root}/config.yaml",
                "refName": "main",
                "entrypoint": "scripts/train.sh",
                "batchEntryPoint": "scripts/run_batch_inference.py",
            },
            "tools": {
                "submitTraining": {
                    "command": f"bash {script_root}/train.sh",
                    "workingDirectory": model_repo_root,
                },
                "submitBatchInference": {
                    "command": f"bash {script_root}/batch_infer.sh",
                    "workingDirectory": model_repo_root,
                },
            },
            "metadata": {"family": "xgboost"},
        }
    ]
}
print(json.dumps(payload))
PY

THINWEDGE_FIXTURE_ENV_REPO_ROOT="$environment_repo_root" \
THINWEDGE_FIXTURE_SCRIPT_ROOT="$script_root" \
THINWEDGE_FIXTURE_RUNPOD_TEMPLATE_ID="$runpod_template_id" \
THINWEDGE_FIXTURE_RUNPOD_GPU_TYPE_ID="$runpod_gpu_type_id" \
THINWEDGE_FIXTURE_RUNPOD_NETWORK_VOLUME_ID="$runpod_network_volume_id" \
THINWEDGE_FIXTURE_RUNPOD_CLOUD_TYPE="$runpod_cloud_type" \
THINWEDGE_FIXTURE_RUNPOD_SUPPORT_PUBLIC_IP="$runpod_support_public_ip" \
THINWEDGE_FIXTURE_RUNPOD_SSH_PUBLIC_KEY="$runpod_ssh_public_key" \
THINWEDGE_FIXTURE_RUNPOD_SSH_PRIVATE_KEY_PATH="$runpod_ssh_private_key_path" \
THINWEDGE_FIXTURE_RUNPOD_IMAGE_NAME="$runpod_image_name" \
THINWEDGE_FIXTURE_RUNPOD_DOCKER_ENTRYPOINT_JSON="$runpod_docker_entrypoint_json" \
THINWEDGE_FIXTURE_RUNPOD_DOCKER_START_CMD_JSON="$runpod_docker_start_cmd_json" \
THINWEDGE_FIXTURE_RUNPOD_GLOBAL_NETWORKING="$runpod_global_networking" \
THINWEDGE_FIXTURE_RUNPOD_CONTROL_TOKEN="$runpod_control_token" \
THINWEDGE_FIXTURE_RUNPOD_CONTROL_PORT="$runpod_control_port" \
THINWEDGE_FIXTURE_RUNPOD_CONTROL_SERVER_B64="$control_server_b64" \
THINWEDGE_FIXTURE_RUNTIME_FAMILY="$runtime_family" \
python3 - <<'PY' | thinwedge_write_json_file "$environments_path"
import json
import os

script_root = os.environ["THINWEDGE_FIXTURE_SCRIPT_ROOT"]
environment_repo_root = os.environ["THINWEDGE_FIXTURE_ENV_REPO_ROOT"]
network_volume_id = os.environ.get("THINWEDGE_FIXTURE_RUNPOD_NETWORK_VOLUME_ID") or None
ssh_public_key = os.environ.get("THINWEDGE_FIXTURE_RUNPOD_SSH_PUBLIC_KEY") or None
ssh_private_key_path = os.environ.get("THINWEDGE_FIXTURE_RUNPOD_SSH_PRIVATE_KEY_PATH") or None
image_name = os.environ.get("THINWEDGE_FIXTURE_RUNPOD_IMAGE_NAME") or None
docker_entrypoint_json = os.environ.get("THINWEDGE_FIXTURE_RUNPOD_DOCKER_ENTRYPOINT_JSON") or ""
docker_start_cmd_json = os.environ.get("THINWEDGE_FIXTURE_RUNPOD_DOCKER_START_CMD_JSON") or ""
runpod = {
    "templateId": os.environ["THINWEDGE_FIXTURE_RUNPOD_TEMPLATE_ID"],
    "gpuCount": 1,
    "gpuTypeId": os.environ["THINWEDGE_FIXTURE_RUNPOD_GPU_TYPE_ID"],
    "volumeMountPath": "/workspace",
    "workspacePath": "/workspace/thinwedge/env-pricing",
    "exposedHttpPort": int(os.environ["THINWEDGE_FIXTURE_RUNPOD_CONTROL_PORT"]),
    "supportsSsh": True,
    "name": "thinwedge-pricing-env",
    "cloudType": os.environ["THINWEDGE_FIXTURE_RUNPOD_CLOUD_TYPE"],
    "globalNetworking": os.environ["THINWEDGE_FIXTURE_RUNPOD_GLOBAL_NETWORKING"].lower() == "true",
    "containerDiskInGb": 50,
    "volumeInGb": 100,
    "supportPublicIp": os.environ["THINWEDGE_FIXTURE_RUNPOD_SUPPORT_PUBLIC_IP"].lower() == "true",
    "stopMode": "stop",
    "startupTimeoutSec": 900,
    "env": {
        "THINWEDGE_MODEL_REPOSITORY_ROOT": "/workspace/thinwedge/model-pricing-repo",
        "THINWEDGE_ENV_REPOSITORY_ROOT": "/workspace/thinwedge/env-pricing-repo",
        "THINWEDGE_RUNTIME_FAMILY": os.environ["THINWEDGE_FIXTURE_RUNTIME_FAMILY"],
        "THINWEDGE_CONTROL_TOKEN": os.environ["THINWEDGE_FIXTURE_RUNPOD_CONTROL_TOKEN"],
        "THINWEDGE_CONTROL_PORT": os.environ["THINWEDGE_FIXTURE_RUNPOD_CONTROL_PORT"],
        "THINWEDGE_CONTROL_SERVER_B64": os.environ["THINWEDGE_FIXTURE_RUNPOD_CONTROL_SERVER_B64"],
    }
}
if network_volume_id:
    runpod["networkVolumeId"] = network_volume_id
if ssh_public_key:
    runpod["env"]["SSH_PUBLIC_KEY"] = ssh_public_key
    runpod["env"]["PUBLIC_KEY"] = ssh_public_key
if ssh_private_key_path:
    runpod["sshPrivateKeyPath"] = ssh_private_key_path
if image_name:
    runpod["imageName"] = image_name
if docker_entrypoint_json:
    runpod["dockerEntrypoint"] = json.loads(docker_entrypoint_json)
if docker_start_cmd_json:
    runpod["dockerStartCmd"] = json.loads(docker_start_cmd_json)
payload = {
    "environments": [
        {
            "id": "env-pricing",
            "name": "Pricing GPU",
            "description": "ThinWedge sample pricing environment",
            "tags": ["pricing", "gpu"],
            "visibleToRoles": ["pricing_researcher"],
            "status": "stopped",
            "workingDirectory": f"{environment_repo_root}/workdir",
            "repository": {
                "root": environment_repo_root,
                "refName": "gpu-main",
                "entrypoint": "ops/launch.sh",
            },
            "tools": {
                "launch": {
                    "command": f"bash {script_root}/launch.sh",
                    "workingDirectory": environment_repo_root,
                },
                "attach": {
                    "command": f"bash {script_root}/attach.sh",
                    "workingDirectory": environment_repo_root,
                },
                "stop": {
                    "command": f"bash {script_root}/stop.sh",
                    "workingDirectory": environment_repo_root,
                },
            },
            "metadata": {
                "provider": "runpod",
                "runpod": runpod,
            },
        }
    ]
}
print(json.dumps(payload))
PY

printf 'Seeded ThinWedge ML fixtures under %s\n' "$thinwedge_home/thinwedge/ml"
