
[package]
edition.workspace = true
license.workspace = true
name = "thinwedge-cloud-tasks-mock-client"
version.workspace = true

[lib]
name = "thinwedge_cloud_tasks_mock_client"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
async-trait = { workspace = true }
chrono = { workspace = true }
thinwedge-cloud-tasks-client = { workspace = true }
diffy = { workspace = true }
