# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#package-ecosystem-

version: 2
updates:
  - package-ecosystem: bun
    directory: .github/actions/thinwedge
    schedule:
      interval: weekly
  - package-ecosystem: cargo
    directories:
      - thinwedge-rs
      - thinwedge-rs/*
    schedule:
      interval: weekly
  - package-ecosystem: devcontainers
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: thinwedge-cli
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: rust-toolchain
    directory: thinwedge-rs
    schedule:
      interval: weekly
