[package]
edition.workspace = true
license.workspace = true
name = "thinwedge-model-provider-info"
version.workspace = true

[lib]
doctest = false
name = "thinwedge_model_provider_info"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
thinwedge-api = { workspace = true }
thinwedge-app-server-protocol = { workspace = true }
thinwedge-protocol = { workspace = true }
http = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true, features = ["derive"] }

[dev-dependencies]
thinwedge-utils-absolute-path = { workspace = true }
maplit = { workspace = true }
pretty_assertions = { workspace = true }
tempfile = { workspace = true }
toml = { workspace = true }
