[package]
edition.workspace = true
license.workspace = true
name = "thinwedge-core-api"
version.workspace = true

[lib]
doctest = false
name = "thinwedge_core_api"
path = "src/lib.rs"
test = false

[lints]
workspace = true

[dependencies]
thinwedge-app-server-protocol = { workspace = true }
thinwedge-arg0 = { workspace = true }
thinwedge-analytics = { workspace = true }
thinwedge-config = { workspace = true }
thinwedge-core = { workspace = true }
thinwedge-extension-api = { workspace = true }
thinwedge-home = { workspace = true }
thinwedge-exec-server = { workspace = true }
thinwedge-features = { workspace = true }
thinwedge-login = { workspace = true }
thinwedge-model-provider-info = { workspace = true }
thinwedge-models-manager = { workspace = true }
thinwedge-protocol = { workspace = true }
thinwedge-utils-absolute-path = { workspace = true }
