[package]
name = "thinwedge-arg0"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "thinwedge_arg0"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
thinwedge-apply-patch = { workspace = true }
thinwedge-exec-server = { workspace = true }
thinwedge-linux-sandbox = { workspace = true }
thinwedge-sandboxing = { workspace = true }
thinwedge-shell-escalation = { workspace = true }
thinwedge-utils-absolute-path = { workspace = true }
thinwedge-utils-home-dir = { workspace = true }
dotenvy = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread"] }
