[package]
edition.workspace = true
license.workspace = true
name = "thinwedge-skills"
version.workspace = true
build = "build.rs"

[lib]
doctest = false
name = "thinwedge_skills"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
thinwedge-utils-absolute-path = { workspace = true }
include_dir = { workspace = true }
thiserror = { workspace = true }
