[package]
edition.workspace = true
license.workspace = true
name = "thinwedge-cloud-tasks"
version.workspace = true

[lib]
name = "thinwedge_cloud_tasks"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
clap = { workspace = true, features = ["derive"] }
thinwedge-client = { workspace = true }
thinwedge-cloud-tasks-client = { workspace = true }
# TODO: thinwedge-cloud-tasks-mock-client should be in dev-dependencies.
thinwedge-cloud-tasks-mock-client = { workspace = true }
thinwedge-core = { workspace = true }
thinwedge-git-utils = { workspace = true }
thinwedge-login = { path = "../login" }
thinwedge-model-provider = { workspace = true }
thinwedge-tui = { workspace = true }
thinwedge-utils-cli = { workspace = true }
crossterm = { workspace = true, features = ["event-stream"] }
owo-colors = { workspace = true, features = ["supports-colors"] }
ratatui = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
supports-color = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tokio-stream = { workspace = true }
tracing = { workspace = true, features = ["log"] }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
unicode-width = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
