[package]
name = "thinwedge-utils-oss"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
thinwedge-core = { workspace = true }
thinwedge-lmstudio = { workspace = true }
thinwedge-model-provider-info = { workspace = true }
thinwedge-ollama = { workspace = true }

[lib]
doctest = false
