[package]
edition.workspace = true
license.workspace = true
name = "thinwedge-model-provider"
version.workspace = true

[lib]
doctest = false
name = "thinwedge_model_provider"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
async-trait = { workspace = true }
thinwedge-api = { workspace = true }
thinwedge-agent-identity = { workspace = true }
thinwedge-aws-auth = { workspace = true }
thinwedge-client = { workspace = true }
thinwedge-feedback = { workspace = true }
thinwedge-login = { workspace = true }
thinwedge-model-provider-info = { workspace = true }
thinwedge-models-manager = { workspace = true }
thinwedge-otel = { workspace = true }
thinwedge-protocol = { workspace = true }
thinwedge-response-debug-context = { workspace = true }
http = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["sync", "time"] }
tracing = { workspace = true, features = ["log"] }

[dev-dependencies]
pretty_assertions = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt"] }
wiremock = { workspace = true }
