[package]
edition.workspace = true
license.workspace = true
name = "thinwedge-thread-store"
version.workspace = true

[lib]
name = "thinwedge_thread_store"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true

[dependencies]
chrono = { workspace = true, features = ["serde"] }
thinwedge-git-utils = { workspace = true }
thinwedge-install-context = { workspace = true }
thinwedge-protocol = { workspace = true }
thinwedge-rollout = { workspace = true }
thinwedge-state = { workspace = true }
thinwedge-utils-path = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
uuid = { workspace = true }
